export const workResponse = {
  header: {
    trId: "020012",
    rtnCode: "000000",
    rtnMessage: "성공입니다.",
  },
  body: {
    totCnt: 7,
    headerInfos: [
      {
        idx: 0,
        keyName: "name",
        name: "작업명",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 1,
        keyName: "workNo",
        name: "작업번호",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 2,
        keyName: "programNo",
        name: "프로그램번호",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 3,
        keyName: "orderNo",
        name: "발주번호",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 4,
        keyName: "program",
        name: "프로그램",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 5,
        keyName: "lockStatus",
        name: "LOCK 상태",
        isSort: false,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 6,
        keyName: "details",
        name: "목표/완성/잔여/실패",
        isSort: true,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 7,
        keyName: "fail",
        name: "실패율",
        isSort: true,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 8,
        keyName: "status",
        name: "작업상태",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 9,
        keyName: "register",
        name: "등록일",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 10,
        keyName: "due",
        name: "마감일",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 10,
        keyName: "machineInfo",
        name: "기계정보",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
    ],
    items: [
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_1",
        workNo: "wki_001",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_2",
        workNo: "wki_002",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_3",
        workNo: "wki_003",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_4",
        workNo: "wki_003",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_5",
        workNo: "wki_003",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_6",
        workNo: "wki_003",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_7",
        workNo: "wki_003",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
    ],
  },
};

export const dashboardResponse = {
  header: {
    trId: "020012",
    rtnCode: "000000",
    rtnMessage: "성공입니다.",
  },
  body: {
    totCnt: 2,
    headerInfos: [
      {
        idx: 0,
        keyName: "name",
        name: "작업명",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 1,
        keyName: "goal",
        name: "목표",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 2,
        keyName: "completed",
        name: "완성",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 3,
        keyName: "remaining",
        name: "잔여",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 4,
        keyName: "failed",
        name: "실패",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 5,
        keyName: "status",
        name: "작업상태",
        isSort: false,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 6,
        keyName: "failureRate",
        name: "실패율",
        isSort: true,
        isFilter: false,
        isDisplay: true,
      },
      
    ],
    items: [
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 20000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 10000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 40000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 30000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 60000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 20000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 10000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 40000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 30000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 60000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
    ],
  },
};


export const serialNumberResponse = {
  header: {
    trId: "020012",
    rtnCode: "000000",
    rtnMessage: "성공입니다.",
  },
  body: {
    totCnt: 10,
    headerInfos: [
      {
        idx: 0,
        keyName: "productName",
        name: "제품명",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 1,
        keyName: "testCode",
        name: "테스트 코드",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 2,
        keyName: "location",
        name: "Location",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 3,
        keyName: "count",
        name: "Count",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 4,
        keyName: "todaycount",
        name: "Today_Count",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
     
    ],
    items: [
      {
        productName: "G1_REV2_HAIER_uDFN_I2C_1",
        testCode: "G1_REV2_HAIER_uDFN_I2C",
        location: "2",
        count: "108813",
        todayCount: "3048",
        
      },
      {
        productName: "G2_REV2_HAIER_uDFN_I2C_1",
        testCode: "G1_REV2_HAIER_uDFN_I2C",
        location: "2",
        count: "2353023",
        todayCount: "518",
        
      },
      {
        productName: "G3_REV2_HAIER_uDFN_I2C_1",
        testCode: "G1_REV2_HAIER_uDFN_I2C",
        location: "2",
        count: "3939",
        todayCount: "170",
        
      },
      {
        productName: "G4_REV2_HAIER_uDFN_I2C_1",
        testCode: "G1_REV2_HAIER_uDFN_I2C",
        location: "2",
        count: "770114",
        todayCount: "442",
        
      },
      {
        productName: "G5_REV2_HAIER_uDFN_I2C_1",
        testCode: "G1_REV2_HAIER_uDFN_I2C",
        location: "2",
        count: "632339",
        todayCount: "15",
        
      },
      {
        productName: "G6_REV2_HAIER_uDFN_I2C_1",
        testCode: "G1_REV2_HAIER_uDFN_I2C",
        location: "2",
        count: "2779699",
        todayCount: "1",
        
      },
      {
        productName: "G7_REV2_HAIER_uDFN_I2C_1",
        testCode: "G1_REV2_HAIER_uDFN_I2C",
        location: "2",
        count: "0",
        todayCount: "0",
        
      },
      {
        productName: "G8_REV2_HAIER_uDFN_I2C_1",
        testCode: "G1_REV2_HAIER_uDFN_I2C",
        location: "2",
        count: "6856",
        todayCount: "0",
        
      },
      {
        productName: "G9_REV2_HAIER_uDFN_I2C_1",
        testCode: "G1_REV2_HAIER_uDFN_I2C",
        location: "2",
        count: "0",
        todayCount: "0",
        
      },
      {
        productName: "G10_REV2_HAIER_uDFN_I2C_1",
        testCode: "G1_REV2_HAIER_uDFN_I2C",
        location: "2",
        count: "411832",
        todayCount: "7883",
        
      },

      
    ],
  },
};


export const codeInfoResponse = {
  header: {
    trId: "020012",
    rtnCode: "000000",
    rtnMessage: "성공입니다.",
  },
  body: {
    totCnt: 5,
    headerInfos: [
      {
        idx: 0,
        keyName: "codename",
        name: "코드명",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 1,
        keyName: "group",
        name: "그룹",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 2,
        keyName: "description",
        name: "설명",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 3,
        keyName: "status",
        name: "상태",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 4,
        keyName: "enum",
        name: "코드ENUM",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      
      
    ],
    items: [
      {
        codename: "SESSION_RESULT",
        group: "M",
        description: "세션결과 코드",
        status: "활성",
        enum: "코드 enum"
      },
      {
        codename: "HANDLER_STATUS",
        group: "H",
        description: "핸들러 상태 코드",
        status: "활성",
        enum: "코드 enum"
      },
      {
        codename: "BURNING_DETAIL_STATUS",
        group: "",
        description: "굽기 상세 상태 코드",
        status: "활성",
        enum: "코드 enum"
      },
      {
        codename: "SESSION_STATUS",
        group: "",
        description: "세션 상태 코드",
        status: "활성",
        enum: "코드 enum"
      },
      // {
      //   codename: "WORK_STATUS",
      //   group: "W",
      //   description: "작업 상태 코드",
      //   status: "활성",
      //   enum: "코드 enum"
      // },
      // {
      //   codename: "SESSION_RESULT",
      //   group: "M",
      //   description: "세션결과 코드",
      //   status: "활성",
      //   enum: "코드 enum"
      // },
      // {
      //   codename: "HANDLER_STATUS",
      //   group: "H",
      //   description: "핸들러 상태 코드",
      //   status: "활성",
      //   enum: "코드 enum"
      // },
      // {
      //   codename: "BURNING_DETAIL_STATUS",
      //   group: "",
      //   description: "굽기 상세 상태 코드",
      //   status: "활성",
      //   enum: "코드 enum"
      // },
      // {
      //   codename: "SESSION_STATUS",
      //   group: "",
      //   description: "세션 상태 코드",
      //   status: "활성",
      //   enum: "코드 enum"
      // },
      // {
      //   codename: "WORK_STATUS",
      //   group: "W",
      //   description: "작업 상태 코드",
      //   status: "활성",
      //   enum: "코드 enum"
      // },
      // {
      //   codename: "SESSION_RESULT",
      //   group: "M",
      //   description: "세션결과 코드",
      //   status: "활성",
      //   enum: "코드 enum"
      // },
      // {
      //   codename: "HANDLER_STATUS",
      //   group: "H",
      //   description: "핸들러 상태 코드",
      //   status: "활성",
      //   enum: "코드 enum"
      // },
      // {
      //   codename: "BURNING_DETAIL_STATUS",
      //   group: "",
      //   description: "굽기 상세 상태 코드",
      //   status: "활성",
      //   enum: "코드 enum"
      // },
      // {
      //   codename: "SESSION_STATUS",
      //   group: "",
      //   description: "세션 상태 코드",
      //   status: "활성",
      //   enum: "코드 enum"
      // },
      // {
      //   codename: "WORK_STATUS",
      //   group: "W",
      //   description: "작업 상태 코드",
      //   status: "활성",
      //   enum: "코드 enum"
      // },
     
    ],
  },
};

export const settingResponse = {
  header: {
    trId: "020012",
    rtnCode: "000000",
    rtnMessage: "성공입니다.",
  },
  body: {
    totCnt: 7,
    headerInfos: [
      {
        idx: 0,
        keyName: "fileName",
        name: "파일명",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 1,
        keyName: "type",
        name: "종류",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 2,
        keyName: "version",
        name: "버전",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 3,
        keyName: "hash",
        name: "해시",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 4,
        keyName: "fileDetails",
        name: "파일보기",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 5,
        keyName: "download",
        name: "다운로드",
        isSort: false,
        isFilter: true,
        isDisplay: true,
      },
     
    ],
    items: [
      {
        fileName: "[IMB-300]G5_USIM_I9X00_ATR6.3ms_3.3v_v0.2.3_NO_LOCK_20240730.json",
        type: "script",
        version: "",
        hash: "mHwhhO3nEqCTjhjYK4L7oE02RBknAqPyVBRw90a4PUM=",
        fileDetails: "",
        download: "",
      },
      {
        fileName: "[IMB-300]G5_eSIM_I98X0_v0.1.A_20240418.json",
        type: "script",
        version: "",
        hash: "ArcYBH3XAZHMIr3JNRXIWsVrCtBq2lfsAF9zTYeosxI=",
        fileDetails: "",
        download: "",
      },
      {
        fileName: "g3u_rev3_TV3UG4_re.json",
        type: "script",
        version: "",
        hash: "/qY96ZHk+b0hQFxNz5Gd08eljaMpCvUsvemsZijv+cI=",
        fileDetails: "",
        download: "",
      },
      {
        fileName: "g3k_rev3_TKUQ1_re.json",
        type: "script",
        version: "",
        hash: "n5pS6DYObUYpx39yY+b1bXtZPoX2keHt3QR/rqORYS0=",
        fileDetails: "",
        download: "",
      },
      {
        fileName: "g3u_rev3_V3UD1_TV3UD1_TV3UG1_re.json",
        type: "script",
        version: "",
        hash: "F200z+PhQBjVo91dy1jeBu69MTZ/kwH4vV1n9f3A5Y0=",
        fileDetails: "",
        download: "",
      },
    ],
  },
};


