export const workResponse = {
  header: {
    trId: "020012",
    rtnCode: "000000",
    rtnMessage: "성공입니다.",
  },
  body: {
    totCnt: 2,
    headerInfos: [
      {
        idx: 0,
        keyName: "name",
        name: "작업명",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 1,
        keyName: "workNo",
        name: "작업번호",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 2,
        keyName: "programNo",
        name: "프로그램번호",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 3,
        keyName: "orderNo",
        name: "발주번호",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 4,
        keyName: "program",
        name: "프로그램",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 5,
        keyName: "lockStatus",
        name: "LOCK 상태",
        isSort: false,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 6,
        keyName: "details",
        name: "목표/완성/잔여/실패",
        isSort: true,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 7,
        keyName: "fail",
        name: "실패율",
        isSort: true,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 8,
        keyName: "status",
        name: "작업상태",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 9,
        keyName: "register",
        name: "등록일",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 10,
        keyName: "due",
        name: "마감일",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 10,
        keyName: "machineInfo",
        name: "기계정보",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
    ],
    items: [
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_1",
        workNo: "wki_001",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_2",
        workNo: "wki_002",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_3",
        workNo: "wki_003",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_4",
        workNo: "wki_003",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_5",
        workNo: "wki_003",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_6",
        workNo: "wki_003",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
      {
        name: "LGU+(LGU+) g5_usim usim test no lock 07/01_7",
        workNo: "wki_003",
        programNo: "pj-120",
        orderNo: "202040701_6",
        program: "SIMUX_TEST_NO_LOCK_3(G5)",
        lockStatus: false,
        details: "3000/0/3000/3",
        fail: "100%",
        status: "0.00%(중지상태)",
        register: "24/07/30",
        due: "24/07/08",
        machineInfo: "USIM_3",
      },
    ],
  },
};

export const dashboardResponse = {
  header: {
    trId: "020012",
    rtnCode: "000000",
    rtnMessage: "성공입니다.",
  },
  body: {
    totCnt: 2,
    headerInfos: [
      {
        idx: 0,
        keyName: "name",
        name: "작업명",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 1,
        keyName: "goal",
        name: "목표",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 2,
        keyName: "completed",
        name: "완성",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 3,
        keyName: "remaining",
        name: "잔여",
        isSort: false,
        isFilter: false,
        isDisplay: true,
      },
      {
        idx: 4,
        keyName: "failed",
        name: "실패",
        isSort: true,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 5,
        keyName: "status",
        name: "작업상태",
        isSort: false,
        isFilter: true,
        isDisplay: true,
      },
      {
        idx: 6,
        keyName: "failureRate",
        name: "실패율",
        isSort: true,
        isFilter: false,
        isDisplay: true,
      },
      
    ],
    items: [
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 20000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 10000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 40000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 30000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 60000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 20000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 10000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 40000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 30000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
      {
        name: "wki_956_240612-07 lgcns(가온브로드밴드) g3u_rev3 udfn 20k 09/25",
        goal: 60000,
        completed: 17150,
        remaining: 2848,
        failed: 164,
        status: "85.78% (발급중)",
        failureRate: "0.95% (실패율)",
      },
    ],
  },
};
